### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by BorysekOndrej** [matousekm/edulint-vscode#2]
Hi Martin, thank you for creating this VS Code extension. 

While testing it I realized that it currently doesn't work on Windows. The default config of Python installer on Windows creates the executable alias `python` instead of `python3`.  And [currently](https://github.com/matousekm/edulint-vscode/commit/6c5819dbc63feb4d490e0398c66b8cb01fecb5b5#diff-19a9a3efb94bf1b84229bda71ab0ef5badcdbf34ba3a0c9e4152a82c569a21e6R25) this extension always tries to call `python3`.

The extension could monitor which Python executable the VSCode uses, that could be more platform independent.

Do you have any plans to implement that in near future?

**Comment by matousekm** [comment]
Added https://github.com/matousekm/edulint-vscode/commit/b999b2b90f9f178d958bfc69a3aec6dc8df9c63b. What do you think?

**Comment by BorysekOndrej** [comment]
Works great, thank you!
